export const FETCH_POST_REQUEST="FETCH_POST_REQUEST";
export const FETCH_POST_SUCCESS="FETCH_POST_SUCCESS";
export const FETCH_POST_DETAILS_REQUEST="FETCH_POST_DETAILS_REQUEST";
export const FETCH_POST_DETAILS_SUCCESS="FETCH_POST_DETAILS_SUCCESS";
export const FETCH_USER_REQUEST="FETCH_USER_REQUEST";  
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS";
export const ADD_POST="ADD_POST";
